[project]
name = "wordle"
version = "0.1.0"
description = "Play Wordle using Information Theory."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "mypy>=1.13.0",
    "numpy>=2.2.0",
    "pytest>=8.3.4",
]
